[tool.uv]
required-version = ">=0.4"

[tool.uv.workspace]
members = [
  "device/raspi-zero2",
  "server/mqtt_gateway",
  # 後で "server/batch" も足す予定
]

[dependency-groups]
dev = [
  "ruff",
  "ty",
  "pytest",
  "pre-commit",
  "import-linter",
]
